[package]
name = "arp-microsvc"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
#actix-web="0.7"
#pnet_datalink = "0.22.0"
#ipnetwork = "0.12.0"
pnet = "0.22.0"
reqwest = "0.9.11"