[package]
name = "arp-microsvc"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
actix-web="0.7"
ipnetwork = "0.14.0"
pnet = "0.22.0"
reqwest = "0.9.11"
